#:schema node_modules/wrangler/config-schema.json
name = "worker-gentle-lab-f0c4"
main = "src/index.ts"
compatibility_date = "2024-04-30"
compatibility_flags = ["nodejs_compat"]
#node_compat = true

[vars]
NODE_VERSION = 18
